### ISSUE TITLE
是否考虑补充.env.example文件、SQL相关脚本、以及优化README.md以完善项目？

### ISSUE THREAD

**Issue by BerlinWong** [liujuntao123/prompt-manager#2]
经过较长时间的部署，目前出现的问题还是比较多的，大部分问题出现在环境上，主要是环境变量。
虽然README.md中有提及，但是对于部署一个项目来讲还是远远不够的（会报错）。
手动创建数据表的过程如果可以的话，给出CSV或SQL脚本可能体验会更好！
希望作者能添加.env.example文件以及完善README.md
当然这也只是建议🫣，仅仅想更加完整、完善的体验该项目！

**Comment by WyInnovate** [comment]
我感觉缺少clerk相关的环境变量是不是？佬知道要配置哪些clerk相关的环境变量吗？

**Comment by WyInnovate** [comment]
@BerlinWong 大佬好，我创建提示词提示500，我看users表里没数据是因为这个导致的吗？

**Comment by BerlinWong** [comment]
> @BerlinWong ~大佬好，我创建提示词提示500~ ~我看users表里没数据是因为这个导致的吗？~ ~怎么往users表插入数据的没看懂~ users表应该用不到了我觉得，解决了没事了

hh，我想我来晚了，项目立意还是很有趣的

**Comment by WyInnovate** [comment]
> > @BerlinWong ~大佬好，我创建提示词提示500~ ~我看users表里没数据是因为这个导致的吗？~ ~怎么往users表插入数据的没看懂~ users表应该用不到了我觉得，解决了没事了
> 
> 
> 
> hh，我想我来晚了，项目立意还是很有趣的

有新版了好耶，等明天看教程😊

**Comment by BerlinWong** [comment]
Thanks for your contributions, a new version has been released and this issue is closed.

**Comment by WyInnovate** [comment]
> Thanks for your contributions, a new version has been released and this issue is closed.

Bad news, it has now reverted back to an old version because there are some unresolved issues

**Comment by BerlinWong** [comment]
Rolling back is also quite normal. Your project code shows that there was its own management system before clerk was added, and it had reserved functions like public and sharing. Since it was switched to clerk, user information couldn't be stored in the database. Rolling back can help clarify the thought process better. Looking forward to future versions, once released, I will redeploy the project on Vercel. Hit the jackpot! 🎉🎉🎉
